In [10]:
#In class programming:
# 1. Create a class Employee and then do the following
# • Create a data member to count the number of Employees
# • Create a constructor to initialize name, family, salary, department
# • Create a function to average salary
# • Create a Fulltime Employee class and it should inherit the properties of Employee class
# • Create the instances of Fulltime Employee class and Employee class and call their member functions.

In [9]:
class Employee:
    """
    Generic Employee class with name, family, salary and department
    """

    # data member to count the number of Employees
    no_of_employees = 0

    def __init__(self, name, family_name, salary, department):
        self.__name = name
        self.__family_name = family_name
        self.salary = salary
        self.__department = department
        Employee.no_of_employees += 1  #a=a+1    a+=1

    @staticmethod
    def average_salary(employees):
        """
        function to average salary
        """
        sum = 0
        for employee in employees:
            sum += employee.salary
        return sum / Employee.no_of_employees


class FulltimeEmployee(Employee):
    """
    Full Time Employee is a sub class of Employee
    """

    def __init__(self, name, family_name, salary, department):
        super().__init__(name, family_name, salary, department)

    def full_time_benefits(self):
        print("Few benefits as full time employee.")


def main():
    employees = []
    fte1 = FulltimeEmployee("Employee1", "FamilyName1", 120000, "Management")
    fte1.full_time_benefits()
    employees.append(fte1)
    fte2 = FulltimeEmployee("Employee2", "FamilyName2", 180000, "RnD")
    employees.append(fte2)
    emp1 = Employee("Employee3", "FamilyName3", 160000, "Marketing")
    employees.append(emp1)
    emp2 = Employee("Employee4", "FamilyName4", 135000, "HR")
    employees.append(emp2)
    print("Average salary:", FulltimeEmployee.average_salary(employees))


if __name__ == "__main__": #revoking  the main function
    main()

Few benefits as full time employee.
Average salary: 148750.0


In [1]:
import numpy as np


def replace_maxmium(array, replace_value, axis):
    """ choose from x or y depending on condition: np.where(condition, x, y) """  # defing function and passing arguments
    output = np.where(array == np.max(
        array, axis=1).reshape(-1, 1), 0 * array, array)
    return output




# Using NumPy create random vector of size 20 having only float
# in the range 1-20.

# continuous uniform distribution in [0, 1).
# To sample Unif[a, b): (b - a) * random_sample() + a
random20 = np.random.random_sample(20) * 20 + 1

# Reshape the array to 4 by 5
random20_4by5 = random20.reshape((4,5))

# Replace the max in each row by 0(axis=1)
print(replace_maxmium(random20_4by5, 0, 1))



[[17.28496217  9.54710987  0.          6.4544158  10.90285218]
 [ 3.07767105  0.         13.61704921 15.94334051 16.23059947]
 [ 0.         12.87749898  9.94870617  9.42406751 17.55273446]
 [10.0135727   0.         10.75807659 14.10727285  4.45711656]]
